[project]
name = "personal-backend-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "bleach>=6.2.0",
    "boto3>=1.42.45",
    "boto3-stubs>=1.42.48",
    "fastapi>=0.128.7",
    "httpx2>=2.2.0",
    "httpx2-pytest>=1.0.1",
    "mangum>=0.21.0",
    "markdown>=3.7",
    "pendulum>=3.2.0",
    "pydantic>=2.12.5",
    "pydantic-settings>=2.14.2",
    "pyjwt>=2.10.1",
    "python-dotenv>=1.1.0",
    "python-slugify>=8.0.4",
    "sshfs>=2025.2.0",
    "unidecode>=1.4.0",
    "uvicorn>=0.40.0",
]

[dependency-groups]
dev = [
    "aws-lambda-powertools[validation]>=3.24.0",
    "bandit>=1.9.3",
    "faker>=37.3.0",
    "moto>=5.1.21",
    "pytest>=9.0.2",
    "pytest-cov>=7.1.0",
    "pytest-env>=1.2.0",
    "pytest-mock>=3.15.1",
    "pytest-xdist>=3.8.0",
    "ruff>=0.15.0",
    "ty>=0.0.28",
]

[tool.pytest.ini_options]
addopts = "--cache-clear --cov-branch --cov-report term --cov=app/ -n auto -r f"
env = [
    "APP_NAME=personal-backend-service",
    "ATTACHMENTS_BUCKET_NAME=attachments",
    "AWS_ACCESS_KEY_ID=access_key_id",
    "AWS_DEFAULT_REGION=eu-central-1",
    "AWS_SECRET_ACCESS_KEY=secret_access_key",
    "DEBUG=true",
    "DEFAULT_TIMEZONE=Europe/Budapest",
    "JWT_SECRET_SSM_PARAM_NAME=/dev/secrets/secret",
    "JWT_SECRET_SSM_PARAM_VALUE=9f4a2c8e1b7d0f3a6e5c9b2a4d7f0e1c3f8a9c7e2b1d0f5a6e4c8b9a2d7f0e1c",
    "LOG_LEVEL=INFO",
    "RATE_LIMIT_DURATION_IN_SECONDS=60",
    "RATE_LIMIT_REQUESTS=60",
    "RATE_LIMITING=true",
    "SSH_HOST=localhost",
    "SSH_PASSWORD=fishing",
    "SSH_USERNAME=sam",
    "SSH_ROOT_PATH=/root",
    "STAGE=test"
]
norecursedirs = [
    "tests/helpers",
]
pythonpath = [
    ".",
    "app",
]
testpaths = [
    "tests"
]
