service: personal-backend-service
frameworkVersion: '3'
plugins:
  - serverless-offline
  - serverless-python-requirements
custom:
  pythonRequirements:
    dockerImage: mlupin/docker-lambda:python3.9-build
    dockerizePip: false
    layer: true
    slim: true
    strip: false
    zip: true
functions:
  app:
    environment:
      APP_NAME: ${env:APP_NAME}
      APP_STAGE: ${env:APP_STAGE}
      APP_TIMEZONE: ${env:APP_TIMEZONE}
      CACHE_SERVICE_BASE_URL: ${env:CACHE_SERVICE_BASE_URL}
      JWT_SECRET: ${env:JWT_SECRET}
    events:
      - httpApi: '*'
    handler: app.main.handler
    layers:
      - Ref: PythonRequirementsLambdaLayer
package:
  patterns:
    - '!.git/**'
    - '!.gitignore'
    - '!.DS_Store'
    - '!npm-debug.log'
    - '!.serverless/**'
    - '!.serverless_plugins/**'
    - '!.venv/**'
provider:
  name: aws
  region: eu-central-1
  runtime: python3.9
  stage: dev
  tracing:
    lambda: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:UpdateItem
          Resource: ${env:AWS_ARN_DYNAMODB}
useDotenv: true
