service: personal-backend-service
frameworkVersion: '3'
plugins:
  - serverless-offline
  - serverless-python-requirements
custom:
  pythonRequirements:
    dockerImage: public.ecr.aws/sam/build-python3.12
    dockerizePip: 'non-linux'
    layer: true
    slim: true
    zip: true
functions:
  app:
    environment:
      APP_NAME: ${env:APP_NAME}
      APP_TIMEZONE: ${env:APP_TIMEZONE}
      CACHE_SERVICE_BASE_URL: ${env:CACHE_SERVICE_BASE_URL}
      DEBUG: ${env:DEBUG}
      JWT_SECRET: ${env:JWT_SECRET}
      LOG_LEVEL: DEBUG
      POWERTOOLS_LOGGER_LOG_EVENT: true
      POWERTOOLS_METRICS_NAMESPACE: personal-backend-service-metrics
      POWERTOOLS_SERVICE_NAME: personal-backend-service
      POWERTOOLS_TRACE_DISABLED: false
      POWERTOOLS_DEBUG: false
      STAGE: ${env:STAGE}
    events:
      - httpApi: '*'
    handler: app.main.handler
    layers:
      - arn:aws:lambda:${aws:region}:017000801446:layer:AWSLambdaPowertoolsPythonV2:20
      - Ref: PythonRequirementsLambdaLayer
package:
  patterns:
    - '!.git/**'
    - '!.gitignore'
    - '!.DS_Store'
    - '!npm-debug.log'
    - '!.serverless/**'
    - '!.serverless_plugins/**'
    - '!.venv/**'
  excludeDevDependencies: true
provider:
  name: aws
  memorySize: 512
  region: ${env:AWS_REGION, 'eu-central-1'}
  runtime: python3.12
  stage: dev
  tracing:
    lambda: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:UpdateItem
          Resource: ${env:AWS_ARN_DYNAMODB}
useDotenv: true
