service: personal-backend-service
frameworkVersion: '3'
plugins:
  - serverless-offline
  - serverless-python-requirements
custom:
  pythonRequirements:
    dockerImage: public.ecr.aws/sam/build-python3.12
    dockerizePip: 'non-linux'
    dockerRunCmdExtraArgs: ['--platform', 'linux/amd64']
    layer: true
    slim: false
functions:
  fastapi:
    environment:
      APP_NAME: ${env:APP_NAME}
      APP_TIMEZONE: ${env:APP_TIMEZONE}
      CACHE_SERVICE_BASE_URL: ${env:CACHE_SERVICE_BASE_URL}
      DEBUG: ${env:DEBUG}
      JWT_SECRET: ${env:JWT_SECRET}
      LOG_LEVEL: DEBUG
      POWERTOOLS_LOGGER_LOG_EVENT: true
      POWERTOOLS_SERVICE_NAME: personal-backend-service
      POWERTOOLS_DEBUG: false
      RATE_LIMIT_DURATION_IN_SECONDS: ${env:RATE_LIMIT_DURATION_IN_SECONDS}
      RATE_LIMIT_REQUESTS: ${env:RATE_LIMIT_REQUESTS}
      STAGE: ${env:STAGE}
    events:
      - httpApi: '*'
    handler: app.main.handler
    layers:
      - arn:aws:lambda:${aws:region}:017000801446:layer:AWSLambdaPowertoolsPythonV2:73
      - Ref: PythonRequirementsLambdaLayer
package:
  patterns:
    - '!.DS_Store'
    - '!.coverage'
    - '!.env'
    - '!.git/**'
    - '!.idea/**'
    - '!.mypy_cache/**'
    - '!.pytest_cache/**'
    - '!.serverless/**'
    - '!.serverless_plugins/**'
    - '!.terraform/**'
    - '!.terraform.lock.hcl'
    - '!.venv/**'
    - '!coverage.xml'
    - '!htmlcov/**'
    - '!node_modules/**'
provider:
  name: aws
  architecture: x86_64
  memorySize: 512
  region: ${env:AWS_REGION, "eu-central-1"}
  runtime: python3.12
  stage: ${opt:stage, 'dev'}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:UpdateItem
          Resource:
            - !GetAtt postsTable.Arn
            - !Sub ${postsTable.Arn}/index/PostPathIndex
            - !Sub ${postsTable.Arn}/index/TitleIndex
            - !Sub ${postsTable.Arn}/index/CreatedAtIndex
resources:
  Resources:
    postsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.stage}-posts
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: post_path
            AttributeType: S
          - AttributeName: title
            AttributeType: S
          - AttributeName: created_at
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: PostPathIndex
            KeySchema:
            - AttributeName: post_path
              KeyType: HASH
            Projection:
              ProjectionType: 'ALL'
          - IndexName: TitleIndex
            KeySchema:
            - AttributeName: title
              KeyType: HASH
            Projection:
              ProjectionType: 'ALL'
          - IndexName: CreatedAtIndex
            KeySchema:
            - AttributeName: created_at
              KeyType: HASH
            Projection:
              ProjectionType: 'ALL'
        BillingMode: PAY_PER_REQUEST
useDotenv: true
