name: Pycodestyle

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install pipenv
      run: |
        python -m pip install --upgrade pipenv wheel
        pipenv install
    - name: Analysing the code with pycodestyle
      run: |
        pycodestyle --ignore=E501 app/ tests/
