name: Pycodestyle

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      id: python-3_9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install pipenv
      run: |
        python -m pip install --upgrade pipenv wheel
    - uses: actions/cache@v3
      id: cache-pipenv
      with:
        path: ~/.local/share/virtualenvs
        key: ${{ runner.os }}-python-${{ steps.python-3_99.outputs.python-version }}-pipenv-${{ hashFiles('Pipfile.lock') }}
    - name: Install packages
      if: steps.cache-pipenv.outputs.cache-hit != 'true'
      run: |
        pipenv install --dev
    - name: Analysing the code with pycodestyle
      run: |
        pipenv run pycodestyle --ignore=E501 app/ tests/
