name: SonarQube

on:
  workflow_run:
    workflows: ["Check codestyle and test"]
    types:
      - completed

jobs:
  name: Analyze code with SonarQube
    - name: Fix source path in coverage.xml
      run: |
        python utils/coverage.py --coverage-file coverage.xml --find $GITHUB_WORKSPACE --replace /github/workspace
    - name: Scan with Sonar scanner
      uses: sonarsource/sonarqube-scan-action@master
      with:
        args: >
          -Dsonar.language=python
          -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
          -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
          -Dsonar.python.coverage.reportPaths=coverage.xml
          -Dsonar.python.version=3.9
          -Dsonar.sources=app
          -Dsonar.tests=tests
      env:
        SONAR_HOST_URL: https://sonarcloud.io
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
